# Generated by Django 4.2.4 on 2023-08-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("department", models.CharField(max_length=5)),
                ("salary", models.IntegerField()),
                ("status", models.BooleanField()),
            ],
        ),
    ]
